[language-server]
typescript-ls = { command = "typescript-language-server", args = [
  "--stdio",
], config.hostInfo = "helix" }

[[language]]
name = "json"
auto-format = true
formatter = { command = "npx", args = [
  "prettier",
  "--stdin-filepath",
  "${buffer_name}",
] }
language-servers = [{ name = "vscode-json-language-server" }]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "npx", args = [
  "prettier",
  "--stdin-filepath",
  "${buffer_name}",
] }
language-servers = [{ name = "typescript-ls" }]
